version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "template/{% if use_git and dev_platform == 'GitHub' %}.github{% endif %}/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependencies: "
      include: scope
    groups:
      actions:
        patterns:
          - "*"
