version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "dependencies: "
      include: scope
    groups:
      actions:
        patterns:
          - "*"
